# Generated by Django 6.0 on 2025-12-27 11:40

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.CharField()),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Natija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('javob', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Exam Code')),
                ('expire_date', models.DateField(blank=True, default=datetime.datetime(2025, 12, 28, 11, 40, 8, 381173, tzinfo=datetime.timezone.utc), verbose_name='Expire Date')),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.guruh')),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='common.kurs')),
                ('Natija', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.natija')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Savol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matn', models.TextField()),
                ('variant_a', models.CharField()),
                ('variant_b', models.CharField()),
                ('variant_c', models.CharField()),
                ('variant_d', models.CharField()),
                ('javob', models.CharField(choices=[('variant_a', 'variant_a'), ('variant_b', 'variant_b'), ('variant_c', 'variant_c'), ('variant_d', 'variant_d')])),
                ('kurs', models.ManyToManyField(related_name='kurslar', to='common.kurs')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='natija',
            name='savol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.savol'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=20, verbose_name='Familiya')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='common.exam')),
            ],
        ),
        migrations.AddField(
            model_name='natija',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.student'),
        ),
    ]
