# Generated by Django 6.0 on 2025-12-13 10:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.IntegerField(unique=True)),
                ('expire_date', models.DateField()),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.guruh')),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.kurs')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Savol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField()),
                ('variant_a', models.CharField()),
                ('variant_b', models.CharField()),
                ('variant_c', models.CharField()),
                ('variant_d', models.CharField()),
                ('javob', models.CharField(choices=[('variant_a', 'variant_a'), ('variant_b', 'variant_b'), ('variant_c', 'variant_c'), ('variant_d', 'variant_d')])),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.kurs')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=20, verbose_name='Familiya')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='common.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Natija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('javob', models.CharField()),
                ('savol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.savol')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.student')),
            ],
        ),
    ]
