# Generated by Django 6.0 on 2026-01-08 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='expire_date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 1, 9, 9, 24, 20, 391142, tzinfo=datetime.timezone.utc), verbose_name='Expire Date'),
        ),
    ]
