# Generated by Django 6.0 on 2025-12-13 10:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='Natija',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.natija'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='code',
            field=models.IntegerField(blank=True, unique=True, verbose_name='Exam Code'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='expire_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 12, 14, 10, 37, 1, 24775, tzinfo=datetime.timezone.utc), verbose_name='Expire Date'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='kurs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='common.kurs'),
        ),
    ]
