# Generated by Django 6.0 on 2025-12-13 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_exam_natija_alter_exam_code_alter_exam_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='code',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Exam Code'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='expire_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 12, 14, 10, 40, 23, 949424, tzinfo=datetime.timezone.utc), verbose_name='Expire Date'),
        ),
    ]
