# Generated by Django 6.0 on 2025-12-20 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_exam_code_alter_exam_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='expire_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 12, 21, 9, 55, 1, 625860, tzinfo=datetime.timezone.utc), verbose_name='Expire Date'),
        ),
        migrations.RemoveField(
            model_name='savol',
            name='kurs',
        ),
        migrations.AddField(
            model_name='savol',
            name='kurs',
            field=models.ManyToManyField(related_name='kurslar', to='common.kurs'),
        ),
    ]
